table 'Cadastro Cientes'
	lineageTag: 9bd2a547-8c58-41e8-81b8-f04b67511c8c

	column 'Id Cliente'
		dataType: int64
		formatString: 0
		lineageTag: 56ccc13f-e5db-4bea-bc55-1c6344fbeee9
		summarizeBy: none
		sourceColumn: Id Cliente

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: 0800885e-cd72-4ba4-9dfc-d8c003390b98
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column 'Data de Nacimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 636fb132-7485-4df7-a402-937837c2a413
		summarizeBy: none
		sourceColumn: Data de Nacimento

		variation Variation
			isDefault
			relationship: bea33648-365c-44fb-9cfb-fd979c9a28d7
			defaultHierarchy: LocalDateTable_e7ee3278-0d14-4c60-90bd-a0760e41aba4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cliente
		dataType: string
		lineageTag: 65c3cd3e-09a7-4d6e-987d-c405338db11b
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: b2f75f34-6c97-451f-b812-e707343085ad
		summarizeBy: sum
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column 'Faixa etária'
		dataType: string
		lineageTag: 57d893b2-2a0f-496d-b6f2-ef2515585e31
		summarizeBy: none
		sourceColumn: Faixa etária

		annotation SummarizationSetBy = Automatic

	partition 'Cadastro Cientes' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Iasmin Meneses\Downloads\drive-download-20250621T180504Z-1-001\Cadastro Clientes.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Id Cliente", Int64.Type}, {"Nome Completo", type text}, {"Genero", type text}, {"Data de Nacimento", type date}}),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Tipo Alterado", "Personalizar", each Text.Combine({Text.Middle([Nome Completo], 4), " ", Text.Start([Nome Completo], 2)}), type text),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Personalizada Adicionada",{{"Personalizar", "Cliente"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"Nome Completo"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas","F","Feminino",Replacer.ReplaceText,{"Genero"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","M","Masculino",Replacer.ReplaceText,{"Genero"}),
				    #"Idade Inserida" = Table.AddColumn(#"Valor Substituído1", "Idade", each Date.From(DateTime.LocalNow()) - [Data de Nacimento], type duration),
				    #"Total de Anos Calculado" = Table.TransformColumns(#"Idade Inserida",{{"Idade", each Duration.TotalDays(_) / 365, type number}}),
				    #"Arredondado para Baixo" = Table.TransformColumns(#"Total de Anos Calculado",{{"Idade", Number.RoundDown, Int64.Type}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Arredondado para Baixo", "Faixa etária", each if [Idade] <= 25 then "Jovem" else if [Idade] <= 55 then "Adulto" else "Sênior"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Faixa etária", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

